name: petpal
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.6.0
  google_nav_bar: ^5.0.6
  path_provider: ^2.1.5
  flutter_dotenv: ^5.1.0
  logging: ^1.2.0
  barcode_widget: ^2.0.4
  simple_barcode_scanner: ^0.3.0
  http: ^1.3.0
  intl: ^0.20.2
  image_picker: ^1.1.2
  cloudinary: ^1.2.0
  cloudinary_api: ^1.1.0
  qr_flutter: ^4.1.0
  share_plus: ^10.1.4
  flutter_speed_dial: ^7.0.0
  pdf: ^3.11.3
  open_file: ^3.5.10
  printing: ^5.14.2
  url_launcher: ^6.3.1
  dio: ^5.7.0
  crypto: ^3.0.6
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/auth.env
    - assets/images/petpal.png
    - assets/images/man.png
    - assets/images/placeholder.jpg
